### ISSUE TITLE
Non-working code from OpenAI

### ISSUE THREAD

**Issue by shyamalschandra** [openai/grok#22]
Why is this bug happening?

```
(myenv) shyamaluser@Shyamals-iMac grok % ./scripts/train.py 
Namespace(random_seed=-1, gpu=0, max_epochs=None, max_steps=100000, batchsize=0, n_layers=2, n_heads=4, d_model=128, dropout=0.0, weight_noise=0.0, non_linearity='relu', max_context_len=50, math_operator='+', operand_length=None, train_data_pct=5, warmup_steps=10, anneal_lr_steps=100000, anneal_lr=False, max_lr=0.001, weight_decay=0, weight_decay_kind='to_zero', noise_factor=0, save_activations=False, save_outputs=False, logdir='/Users/shyamaluser/grok', datadir='/Users/shyamaluser/grok/data')
Traceback (most recent call last):
  File "/Users/shyamaluser/grok/./scripts/train.py", line 14, in <module>
    print(grok.training.train(hparams))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shyamaluser/grok/grok/training.py", line 703, in train
    model = TrainableTransformer(hparams).float()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shyamaluser/grok/grok/training.py", line 50, in __init__
    self.hparams = hparams  # type: ignore
    ^^^^^^^^^^^^
  File "/Users/shyamaluser/grok/myenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in __setattr__
    super().__setattr__(name, value)
AttributeError: property 'hparams' of 'TrainableTransformer' object has no setter
```

**Comment by sergevar** [comment]
Ask Claude bro

**Comment by wz15712990964** [comment]
I have the same problem, please solve it

**Comment by eftanazer** [comment]
solve this pls, i have same problem

**Comment by SonOfLilit** [comment]
This research repository uses an ancient version of pytorch lightning.

To solve this, install that version (and also an old numpy):

Replace in `setup.py`

```
    install_requires=[
        "pytorch_lightning",
        "blobfile",
        "numpy",
```

with

```
    install_requires=[
        "pytorch_lightning==1.0.0",
        "blobfile",
        "numpy<2",
```

rerun `pip install -e .` and it will train.

**Comment by SonOfLilit** [comment]
I think I also needed `numpy<2` and `protobuf<3.21`
